# IMT 573 - Lab 4 - Data Integration

### Instructions

Before beginning this assignment, please ensure you have access to a working instance of Jupyter Notebooks with Python 3.

1. First, replace the “YOUR NAME HERE” text in the next cell with your own full name. Any collaborators must also be listed in this cell.

2. Be sure to include well-documented (e.g. commented) code cells, figures, and clearly written text  explanations as necessary. Any figures should be clearly labeled and appropriately referenced within the text. Be sure that each visualization adds value to your written explanation; avoid redundancy – you do no need four different visualizations of the same pattern.

3. Collaboration on problem sets and labs is fun, useful, and encouraged. However, each student must turn in an individual write-up in their own words as well as code/work that is their own. Regardless of whether you work with others, what you turn in must be your own work; this includes code and interpretation of results. The names of all collaborators must be listed on each assignment. Do not copy-and-paste from other students’ responses or code - your code should never be on any other student's screen or machine.

4. All materials and resources that you use (with the exception of lecture slides) must be appropriately referenced within your assignment.

Name: Steve Gonzales, Collaborators: None

In this module, we have focused on integrating and cleaning data. In this lab, we'll look at integrating different data sources.

The data we will use comes from the City of Seattle. It consists of police beats in the Seattle area and provides information on their geographic locations. You can learn more about police precincts and beats [here](https://www.seattle.gov/police/about-us/about-policing/precinct-and-patrol-boundaries). We'll use this same dataset in a future problem set. 

The data can be found in the `Police_Beat_and_Precinct_Centerpoints.csv` file.

In [5]:
import os
os.path.abspath("")

'S:\\code\\uw\\IMT573'

In [1]:
import pandas as pd
beats_data = pd.read_csv('Police_Beat_and_Precinct_Centerpoints.csv')
df = beats_data

In [3]:
beats_data.head()

  Name                             Location 1  Latitude  Longitude
0   B1  (47.7097756394592, -122.370990523069)  47.70978 -122.37099
1   B2  (47.6790521901374, -122.391748391741)  47.67905 -122.39175
2   B3  (47.6812920482227, -122.364236159741)  47.68129 -122.36424
3   C1  (47.6342500180223, -122.315684762418)  47.63425 -122.31568
4   C2  (47.6192385752996, -122.313557430551)  47.61924 -122.31356

### Problem 1: Inspection

Inspect the beats data. How many records are there? What are the variables? Is there any missing or seemingly anomolous data?

In [6]:
print(f"There are {len(beats_data):,} total rows in the data set.")
print(f"The variables or columns are {df.columns.tolist()}")

There are 57 total rows in the data set.
The variables or columns are ['Name', 'Location 1', 'Latitude', 'Longitude']

In [7]:
display(df)

        Name                             Location 1  Latitude  Longitude
0         B1  (47.7097756394592, -122.370990523069)  47.70978 -122.37099
1         B2  (47.6790521901374, -122.391748391741)  47.67905 -122.39175
2         B3  (47.6812920482227, -122.364236159741)  47.68129 -122.36424
3         C1  (47.6342500180223, -122.315684762418)  47.63425 -122.31568
4         C2  (47.6192385752996, -122.313557430551)  47.61924 -122.31356
5         C3  (47.6300792887474, -122.292087128251)  47.63008 -122.29209
6   CITYWIDE  (47.6210041048652, -122.332993498998)  47.62100 -122.33299
7         D1  (47.6274421308028, -122.345705781837)  47.62744 -122.34571
8         D2  (47.6256548876049, -122.331370005506)  47.62565 -122.33137
9         D3  (47.6103493249325, -122.328653706199)  47.61035 -122.32865
10         E  (47.6201542748144, -122.304782602556)  47.62015 -122.30478
11        E1  (47.6203486882073, -122.324419823241)  47.62035 -122.32442
12        E2   (47.6118432671102, -122.32016086571)  47.61184 -122.32016
13        E3   (47.603162336406, -122.319319689671)  47.60316 -122.31932
14        F1  (47.5484146593035, -122.354809670155)  47.54841 -122.35481
15        F2  (47.5254502461741, -122.365817548329)  47.52545 -122.36582
16        F3  (47.5261052985115, -122.336388313318)  47.52611 -122.33639
17        G1  (47.6091373306494, -122.307899616793)  47.60914 -122.30790
18        G2  (47.5958952989518, -122.306633195511)  47.59590 -122.30663
19        G3  (47.6031821881675, -122.292398835358)  47.60318 -122.29240
20        J1   (47.676809900774, -122.337899655521)  47.67681 -122.33790
21        J2  (47.6613374516723, -122.363818988307)  47.66134 -122.36382
22        J3  (47.6563781774877, -122.336468775341)  47.65638 -122.33647
23        K1  (47.6077552981764, -122.334107460638)  47.60776 -122.33411
24        K2  (47.5998930290529, -122.326813620856)  47.59989 -122.32681
25        K3  (47.5903972078525, -122.333545010682)  47.59040 -122.33355
26        L1  (47.7265488817709, -122.302631931191)  47.72655 -122.30263
27        L2  (47.7095588837442, -122.303661007867)  47.70956 -122.30366
28        L3  (47.6808531540255, -122.277032733938)  47.68085 -122.27703
29        M1  (47.6157584422587, -122.350867935301)  47.61576 -122.35087
30        M2  (47.6146150193586, -122.340275405136)  47.61462 -122.34028
31        M3  (47.6077571617787, -122.340896390036)  47.60776 -122.34090
32         N  (47.6902980120839, -122.328757390104)  47.69030 -122.32876
33        N1  (47.7226875390406, -122.340459039106)  47.72269 -122.34046
34        N2   (47.698470493249, -122.351867710243)  47.69847 -122.35187
35        N3  (47.7045005246442, -122.329961214037)  47.70450 -122.32996
36        O1  (47.5822859359213, -122.311799603309)  47.58229 -122.31180
37        O2  (47.5656855826482, -122.330941962362)  47.56569 -122.33094
38        O3  (47.5345836385751, -122.303020266287)  47.53458 -122.30302
39        Q1   (47.650261230265, -122.400003042555)  47.65026 -122.40000
40        Q2  (47.6428529450151, -122.362673076853)  47.64285 -122.36267
41        Q3  (47.6269804063179, -122.362807276708)  47.62698 -122.36281
42        R1  (47.5758114569194, -122.288707022144)  47.57581 -122.28871
43        R2   (47.562285343514, -122.304240734006)  47.56229 -122.30424
44        R3  (47.5527951110333, -122.268210782218)  47.55280 -122.26821
45        S1  (47.5439339496481, -122.286476209963)  47.54393 -122.28648
46        S2  (47.5263519484816, -122.274095175041)  47.52635 -122.27410
47        S3  (47.5093533353672, -122.259542630385)  47.50935 -122.25954
48        SE  (47.5476766838051, -122.284789228904)  47.54768 -122.28479
49        SW  (47.5478566154038, -122.361787408364)  47.54786 -122.36179
50        U1  (47.6848677676269, -122.309913082907)  47.68487 -122.30991
51        U2   (47.6585545300635, -122.30659481859)  47.65855 -122.30659
52        U3  (47.6660083487855, -122.312204733721)  47.66601 -122.31220
53         W  (47.6300237833357, -122.368053164444)  47.63002 -122.36805
54        W1  (47.5788164080083, -122.378814011668)  47.57882 -122.37881
55        W2  (47.5607068301888, -122.386946475037)  47.56071 -122.38695
56        W3  (47.5255479889804, -122.384581696918)  47.52555 -122.38458

At first glance the data set looks fairly clean. No NaN, null or mismatched data

In [16]:
# Going to take a lot at the relationship between Location 1' and 'Latitude', 'Longitude' 
# Location 1 seems to be derived from Lat and Lon, but I want to make sure they are all follow the pattern
def compare_coordinates(row):
    loc_str = row['Location 1'].strip('()')  # Remove parentheses
    lat_loc, lon_loc = map(float, loc_str.split(','))  # Split and convert what looks to be lat & lon
    return round(lat_loc, 5) == row['Latitude'] and round(lon_loc, 5) == row['Longitude']

df['Coordinates_Match'] = df.apply(compare_coordinates, axis=1)
display(df)

# Print just the rows where the coordinates don't match:
mismatched_df = df[df['Coordinates_Match'] == False]
if not mismatched_df.empty:
    print("\nRows with Mismatched Coordinates:")
    print(mismatched_df)
else:
    print("\nAll coordinates match.")

,Name,Location 1,Latitude,Longitude,Coordinates_Match
0,B1,"(47.7097756394592, -122.370990523069)",47.70978,-122.37099,True
1,B2,"(47.6790521901374, -122.391748391741)",47.67905,-122.39175,True
2,B3,"(47.6812920482227, -122.364236159741)",47.68129,-122.36424,True
3,C1,"(47.6342500180223, -122.315684762418)",47.63425,-122.31568,True
4,C2,"(47.6192385752996, -122.313557430551)",47.61924,-122.31356,True
5,C3,"(47.6300792887474, -122.292087128251)",47.63008,-122.29209,True
6,CITYWIDE,"(47.6210041048652, -122.332993498998)",47.62100,-122.33299,True
7,D1,"(47.6274421308028, -122.345705781837)",47.62744,-122.34571,True
8,D2,"(47.6256548876049, -122.331370005506)",47.62565,-122.33137,True
9,D3,"(47.6103493249325, -122.328653706199)",47.61035,-122.32865,True
10,E,"(47.6201542748144, -122.304782602556)",47.62015,-122.30478,True
11,E1,"(47.6203486882073, -122.324419823241)",47.62035,-122.32442,True
12,E2,"(47.6118432671102, -122.32016086571)",47.61184,-122.32016,True
13,E3,"(47.603162336406, -122.319319689671)",47.60316,-122.31932,True
14,F1,"(47.5484146593035, -122.354809670155)",47.54841,-122.35481,True
15,F2,"(47.5254502461741, -122.365817548329)",47.52545,-122.36582,True
16,F3,"(47.5261052985115, -122.336388313318)",47.52611,-122.33639,True
17,G1,"(47.6091373306494, -122.307899616793)",47.60914,-122.30790,True
18,G2,"(47.5958952989518, -122.306633195511)",47.59590,-122.30663,True
19,G3,"(47.6031821881675, -122.292398835358)",47.60318,-122.29240,True
20,J1,"(47.676809900774, -122.337899655521)",47.67681,-122.33790,True
21,J2,"(47.6613374516723, -122.363818988307)",47.66134,-122.36382,True
22,J3,"(47.6563781774877, -122.336468775341)",47.65638,-122.33647,True
23,K1,"(47.6077552981764, -122.334107460638)",47.60776,-122.33411,True
24,K2,"(47.5998930290529, -122.326813620856)",47.59989,-122.32681,True
25,K3,"(47.5903972078525, -122.333545010682)",47.59040,-122.33355,True
26,L1,"(47.7265488817709, -122.302631931191)",47.72655,-122.30263,True
27,L2,"(47.7095588837442, -122.303661007867)",47.70956,-122.30366,True
28,L3,"(47.6808531540255, -122.277032733938)",47.68085,-122.27703,True
29,M1,"(47.6157584422587, -122.350867935301)",47.61576,-122.35087,True
30,M2,"(47.6146150193586, -122.340275405136)",47.61462,-122.34028,True
31,M3,"(47.6077571617787, -122.340896390036)",47.60776,-122.34090,True
32,N,"(47.6902980120839, -122.328757390104)",47.69030,-122.32876,True
33,N1,"(47.7226875390406, -122.340459039106)",47.72269,-122.34046,True
34,N2,"(47.698470493249, -122.351867710243)",47.69847,-122.35187,True
35,N3,"(47.7045005246442, -122.329961214037)",47.70450,-122.32996,True
36,O1,"(47.5822859359213, -122.311799603309)",47.58229,-122.31180,True
37,O2,"(47.5656855826482, -122.330941962362)",47.56569,-122.33094,True
38,O3,"(47.5345836385751, -122.303020266287)",47.53458,-122.30302,True
39,Q1,"(47.650261230265, -122.400003042555)",47.65026,-122.40000,True
40,Q2,"(47.6428529450151, -122.362673076853)",47.64285,-122.36267,True
41,Q3,"(47.6269804063179, -122.362807276708)",47.62698,-122.36281,True
42,R1,"(47.5758114569194, -122.288707022144)",47.57581,-122.28871,True
43,R2,"(47.562285343514, -122.304240734006)",47.56229,-122.30424,True
44,R3,"(47.5527951110333, -122.268210782218)",47.55280,-122.26821,True
45,S1,"(47.5439339496481, -122.286476209963)",47.54393,-122.28648,True
46,S2,"(47.5263519484816, -122.274095175041)",47.52635,-122.27410,True
47,S3,"(47.5093533353672, -122.259542630385)",47.50935,-122.25954,True
48,SE,"(47.5476766838051, -122.284789228904)",47.54768,-122.28479,True
49,SW,"(47.5478566154038, -122.361787408364)",47.54786,-122.36179,True
50,U1,"(47.6848677676269, -122.309913082907)",47.68487,-122.30991,True
51,U2,"(47.6585545300635, -122.30659481859)",47.65855,-122.30659,True
52,U3,"(47.6660083487855, -122.312204733721)",47.66601,-122.31220,True
53,W,"(47.6300237833357, -122.368053164444)",47.63002,-122.36805,True
54,W1,"(47.5788164080083, -122.378814011668)",47.57882,-122.37881,True
55,W2,"(47.5607068301888, -122.386946475037)",47.56071,-122.38695,True
56,W3,"(47.5255479889804, -122.384581696918)",47.52555,-122.38458,True

All coordinates match.

The only other thing of note is that the Name column has a few rows with single characters and one that says "CITYWIDE"

### Problem 2: Using an API

We're going to join census data to the beats dataset. To do so, we need to first get census tract information for the beats. 

We'll use the `censusgeocode` package to get census tract information for this task. We have seen how different websites/data sources can have APIs and leverage API keys. Python also has many packages that will leverage APIs and `censusgeocode` is one such package in that it can interact with the US Census' APIs.

To start, import the `censusgeocode` package. As always, if the package does not import, you may need to install it first.

In [3]:
!python --version

Python 3.11.6

In [18]:
!pip install censusgeocode

Collecting censusgeocode
  Downloading censusgeocode-0.5.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: requests<3,>=2.27.0 in c:\users\steve\scoop\apps\python311\current\lib\site-packages (from requests[security]<3,>=2.27.0->censusgeocode) (2.31.0)
Collecting requests-toolbelt<1,>=0.9.0 (from censusgeocode)
  Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\steve\scoop\apps\python311\current\lib\site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\steve\scoop\apps\python311\current\lib\site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\steve\scoop\apps\python311\current\lib\site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\steve\scoop\apps\python311\current\lib\site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (2024.2.2)
Downloading censusgeocode-0.5.2-py3-none-any.whl (9.2 kB)
Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
Installing collected packages: requests-toolbelt, censusgeocode
  Attempting uninstall: requests-toolbelt
    Found existing installation: requests-toolbelt 1.0.0
    Uninstalling requests-toolbelt-1.0.0:
      Successfully uninstalled requests-toolbelt-1.0.0
Successfully installed censusgeocode-0.5.2 requests-toolbelt-0.10.1

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import censusgeocode as cg
# FROM python:3.9
# RUN pip install urllib3==1.26.15 requests-toolbelt==0.10.1

ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\Users\steve\scoop\apps\python311\current\Lib\site-packages\urllib3\contrib\__init__.py)

Now, use the [documentation](https://pypi.org/project/censusgeocode/) from the `censusgeocode` package to write a function with the following specifications: 

- the function should accept two arguments - one for longitude and one for latitude (in that order)
- the function should return the census tract number (often coded as `GEOID`) for the inputted latitude and longitude as a string
- the function should be named `get_census_tract`

You can find example outputs below to test your function

In [8]:
get_census_tract(-77.036543, 38.898691) #should return '11001980000'
get_census_tract(-73.985428, 40.748817) #should return '36061007600'
get_census_tract(-118.321495, 34.134117) #should return '06037980009'

'06037980009'

### Problem 3: Get census tracts

Now, for each of the beats in the beats dataset, find the associated census tract. Keep this code as you'll use it in a future problem set.

Census tracts are codes to designate specific locations. The block codes are comprised of state/territory codes, followed by county codes, tract codes, and block codes. You can learn more about this [here](https://transition.fcc.gov/form477/Geo/more_about_census_blocks.pdf) . Confirm that each of the tracts for the beats data is from the state of Washington (code 53) and King County (the county that the city of Seattle is in - code 033).